#!/bin/env bash

# keybind daemon
sxhkd &

# wm-agnostic autostart
$HOME/.local/bin/autostart.sh &

#
# monitor config
#

monitors=($(xrandr --query | grep " connected" | cut -d" " -f1))

# Handle multiple monitors
if [[ $(echo ${monitors[@]} | wc -w) -eq 2 ]]
then # split wses in half, prefer external
    case $HOSTNAME in
        fuglekassa)
            bspc monitor ${monitors[0]} -d {1..5}
            bspc monitor ${monitors[1]} -d {6..10}
            ;;
        *)
            bspc monitor ${monitors[1]} -d {1..5}
            bspc monitor ${monitors[0]} -d {6..10}
            ;;
    esac
    lastd=10
    steamd=8
else # single-monitor layout
    bspc monitor -d {1..8}
    lastd=8
    steamd=7
fi

#
# geometry & settings
#

# borders and gaps
bspc config border_width         3
bspc config window_gap          18
bspc config top_padding         28 # just enough space for my bar!

# layout settings
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true

# focus settings
bspc config pointer_follows_monitor     false
bspc config ignore_ewmh_focus           true

#
# bspwm colors
#

# load pywal colors
source "$HOME/.cache/wal/colors.sh"

# split direction + size indicator
bspc config presel_feedback_color   "$color6"

# border colors
bspc config normal_border_color     "$color8"
bspc config active_border_color     "$color13"
bspc config focused_border_color    "$color12"

#
# window rules
#

# 4 - IDEs
bspc rule -a jetbrains-idea desktop='^4'

# 5 - creativity
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a "com.oracle.javafx.scenebuilder.app.SceneBuilderApp" desktop='^5'

# 8/7 - games (Steam)
bspc rule -a Steam desktop="^${steamd}"

# 10/8 - media and chat
bspc rule -a discord desktop="^${lastd}"
# spotify is weird and unruly

#bspc rule -a Firefox desktop='^2'
bspc rule -a Screenkey manage=off

# floaters
bspc rule -a '*:floater' state=floating # urxvt instances for dialogs
bspc rule -a Lxappearance state=floating
bspc rule -a qt5ct state=floating
bspc rule -a alsamixer state=floating
bspc rule -a "MuseScore: Play Panel" state=floating
bspc rule -a "Pamac-manager" state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Godot state=floating
bspc rule -a XClock state=floating
# javafx apps
bspc rule -a MainApp state=floating
bspc rule -a "\.Main$" state=floating
# remote desktop thing
bspc rule -a RAIL state=floating

# zathura got borked
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

#
# start stuff
# (bspwm specifics)
#

# bspwm starts with audio muted for some reason (on desktop only)
[[ "$HOSTNAME" == "fuglekassa" ]] && pactl set-sink-mute 0 0

# swaaaaallow (clone repo manually, symlink to .local/bin)
command -v pidswallow && pidswallow --loop &
