#! /bin/sh

# keybind daemon
sxhkd &

# autostart up *here*
$HOME/.local/bin/autostart.sh &

#
# bspwm config
#

monitors=($(xrandr --query | grep " connected" | cut -d" " -f1))

# Handle multiple monitors TODO improve...
if [[ $(echo ${monitors[@]} | wc -w) -eq 2 ]]
then # split wses in half, prefer external
    bspc monitor ${monitors[1]} -d 1 2 3 4 5
    bspc monitor ${monitors[0]} -d 6 7 8 9 10
else # single-monitor layout
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi


bspc config border_width         4
bspc config window_gap          12
bspc config top_padding         27 # just enough space for my bar!

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

#
# bspwm colors
#

# load pywal colors
source "$HOME/.cache/wal/colors.sh"

# split direction + size indicator
bspc config presel_feedback_color "$color6"

# border colors
bspc config normal_border_color "$color8"
bspc config active_border_color "$color6"
bspc config focused_border_color "$color7"

#
# window rules
#

# 4 - IDEs
bspc rule -a jetbrains-idea desktop='^4'

# 5 - creativity
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a "com.oracle.javafx.scenebuilder.app.SceneBuilderApp" desktop='^5'

# 8 - games (Steam)
bspc rule -a Steam desktop='^8'

# 10 - media and chat
bspc rule -a discord desktop='^10'

#bspc rule -a Firefox desktop='^2'
bspc rule -a Screenkey manage=off

# floaters
bspc rule -a *:floater state=floating # urxvt instances for dialogs
bspc rule -a Lxappearance state=floating
bspc rule -a qt5ct state=floating
bspc rule -a alsamixer state=floating
bspc rule -a "MuseScore: Play Panel" state=floating
bspc rule -a "Pamac-manager" state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Godot_Engine state=floating
bspc rule -a XClock state=floating
# javafx apps
bspc rule -a MainApp state=floating
bspc rule -a "\.Main$" state=floating
# remote desktop thing
bspc rule -a RAIL state=floating

# zathura got borked
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

#
# start stuff
#

# ahem, why do I need this?
# pulseaudio-ctl mute
# ok here's a better one
pactl set-sink-mute 0 0

# it somehow did not work out being above
# putting it all the way down here
# I don't want that ugly gap...
bspc config top_padding 27
# only a problem after bootup
# -> might be caused by something I launch

